[tool.poetry]
name = "script"
version = "0.1.0"
description = ""
authors = ["masayukeeeee <masayukeeeee@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
