name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Poetry setup
      run: |
        poetry install --no-interaction
    - name: Run pytest
      run: |
        poetry run pytest tests/
    - name: Run mypy
      run: |
        poetry run mypy lib
        poetry run mypy file_organize.py
    - name: Run flake8
      run: |
        poetry run flake8 lib
        poetry run flake8 file_organize.py
